In [ ]:
# @title Default title text
#program 1: Caalculate the total energy from a list
daily_kwh = [100, 200, 300, 400, 500, 600]
total_energy = sum(daily_kwh)
print("Total Energy Used: ", total_energy, "kwh")

Total Energy Used:  2100 kwh

In [ ]:
#program 2" store building usage data
building_usage = {
    "CSE": 100,
    "HOSTEL": 800
}
print("HOSTEL used:", building_usage["HOSTEL"], "kwh")

HOSTEL used: 800 kwh

In [ ]:
#program3:A fuction to calculate electricity cost
def calculate_bill(kwh, rate_per_unit):
  return kwh * rate_per_unit
todays_bill = calculate_bill(480,8)
print("Today's estimated bill is Rs.", todays_bill)

Today's estimated bill is Rs. 3840

In [11]:
#program 4:Read a file line by line
with open("campus_energy.csv", "r") as file:
   for line in file.readlines():
      print(line.strip())

﻿Date,Building,KWH USED,Peak_Hour_Usage
05-10-2026,CSE,100,520
06-10-2026,ECE,200,480
07-10-2026,EEE,300,590
08-10-2026,AIML,400,216
09-10-2026,AIDS,500,468
10-10-2026,CIVIL,600,590
11-10-2026,MECHANICAL,700,620
12-10-2026,HOSTEL,800,780
13-10-2026,IOT,900,820
14-10-2026,CSE,1000,850

In [14]:
#import the pandas libary
import pandas as pd
#load the dataset you created
df = pd.read_csv('campus_energy.csv')
#Display the first few rows of the data
print("Here is the raw data:")
display(df.head())
#group the data to see total usage of the data
building_total = df.groupby('Building')['KWH USED'].sum()
print("Total energy used by each building:")
print(building_total)
print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

         Date Building  KWH USED  Peak_Hour_Usage
0  05-10-2026      CSE       100              520
1  06-10-2026      ECE       200              480
2  07-10-2026      EEE       300              590
3  08-10-2026     AIML       400              216
4  09-10-2026     AIDS       500              468

Total energy used by each building:
Building
AIDS           500
AIML           400
CIVIL          600
CSE           1100
ECE            200
EEE            300
HOSTEL         800
IOT            900
MECHANICAL     700
Name: KWH USED, dtype: int64

Statistical Summary:

          KWH USED  Peak_Hour_Usage
count    10.000000        10.000000
mean    550.000000       593.400000
std     302.765035       191.237026
min     100.000000       216.000000
25%     325.000000       490.000000
50%     550.000000       590.000000
75%     775.000000       740.000000
max    1000.000000       850.000000

In [17]:
# Create the README.md file and write a message inside it
with open("README.md", "w") as file:
  file.write("# Smart Campus Energy Project\n")
  file.write("This repository contains my Week 1 hands-on Python and pandas assignments.\n")
  file.write("Created by: [Yamini Velugu]")

print("README.md has been successfully created!")

README.md has been successfully created!